"""Add decimals field to tokens

Revision ID: ecd801f20509
Revises: 883b9e5efa87
Create Date: 2025-03-12 17:19:52.041412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd801f20509'
down_revision: Union[str, None] = '883b9e5efa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('decimals', sa.Integer(), nullable=True))
    with op.batch_alter_table('tokens') as batch_op:
        batch_op.alter_column(
            'min_amount',
            existing_type=sa.Numeric(),
            type_=sa.BigInteger(),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'min_amount',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('tokens', 'decimals')
    # ### end Alembic commands ###
